Skip to content
Navigation Menu
strapi
documentation

Type / to search
Code
Issues
42
Pull requests
12
Discussions
Actions
Projects
3
Security
Insights
Settings
Sync Content to Next Branch
Content-type Builder revamp (beta release) #11
Jobs
Run details
create-pr-for-labeled
failed now in 15s
Search logs
1s
12s
   * [new tag]           v5.6.1                  -> v5.6.1
   * [new tag]           v5.6.2                  -> v5.6.2
   * [new tag]           v5.6.3                  -> v5.6.3
   * [new tag]           v5.6.4                  -> v5.6.4
   * [new tag]           v5.7.0                  -> v5.7.0
   * [new tag]           v5.8.0                  -> v5.8.0
   * [new tag]           v6.0.0                  -> v6.0.0
   * [new tag]           v6.0.0-beta             -> v6.0.0-beta
   * [new tag]           v6.0.1                  -> v6.0.1
   * [new tag]           v6.0.2                  -> v6.0.2
   * [new tag]           v6.1.0                  -> v6.1.0
   * [new tag]           v6.2.0                  -> v6.2.0
   * [new tag]           v6.2.1                  -> v6.2.1
   * [new ref]           0e88189ceae51cb70f44f3c5268dbe13dc122a67 -> pull/2479/merge
Determining the checkout info
Checking out the ref
/usr/bin/git log -1 --format='%H'
'0e88189ceae51cb70f44f3c5268dbe13dc122a67'
0s
Run git config user.name "GitHub Actions Bot"
0s
Run echo "PR Number: 2479"
PR Number: 2479
PR Title: Content-type Builder revamp (beta release)
Added Label: temp - port to docs-next
1s
Run echo "Checking PR files..."
Checking PR files...
Files in PR:
.github/workflows/sync-content-to-next.yml
docusaurus/docs/cms/features/content-manager.md
docusaurus/docs/cms/features/content-type-builder.md
Content files found:
docusaurus/docs/cms/features/content-manager.md
docusaurus/docs/cms/features/content-type-builder.md
1s
Run echo "Creating PR to next branch..."
  echo "Creating PR to next branch..."
  SOURCE_BRANCH="cms/CTB-revamp"
  SOURCE_REPO="strapi/documentation"
  PR_TITLE="Content-type Builder revamp (beta release)"
  
  echo "Source Branch: $SOURCE_BRANCH"
  echo "Source Repo: $SOURCE_REPO"
  
  # Create a new branch based on next
  TARGET_BRANCH="next-port-pr2479"
  echo "Target Branch: $TARGET_BRANCH"
  
  git fetch origin next
  git checkout -b $TARGET_BRANCH origin/next
  
  # If PR comes from a fork, fetch its changes
  if [ "$SOURCE_REPO" != "strapi/documentation" ]; then
    echo "PR comes from a fork, fetching changes from $SOURCE_REPO"
    git fetch "https://github.com/$SOURCE_REPO.git" $SOURCE_BRANCH
  else
    echo "PR is from the same repo"
    git fetch origin $SOURCE_BRANCH
  fi
  
  # Get content files from PR
  echo "Processing content files from PR..."
  for file in docusaurus/docs/cms/features/content-manager.md
  docusaurus/docs/cms/features/content-type-builder.md
  ; do
    echo "Processing file: $file"
    mkdir -p $(dirname "$file")
    git checkout FETCH_HEAD -- "$file"
  done
  
  # Commit and push
  echo "Committing changes..."
  git add .
  git commit -m "Port PR #2479: $PR_TITLE to next branch"
  
  echo "Pushing branch..."
  git push origin $TARGET_BRANCH
  
  # Create PR to next
  echo "Creating PR from $TARGET_BRANCH to next..."
  gh pr create --base next --head $TARGET_BRANCH \
    --title "[Port to next] $PR_TITLE" \
    --body "Automatic port of PR #2479 to next branch.\n\nOriginal PR: #2479\nCreated automatically after adding the 'temp - port to docs-next' label."
  shell: /usr/bin/bash -e {0}
  env:
0s
0s
